name: Edificio Riviere
description: Sitio web con información relevante para los propietarios e inquilinos del Edificio Riviere
lsi: false
safe: true
source: '/docs'
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
