name: Edificio Riviere
description: Sitio web con información relevante para los propietarios e inquilinos del Edificio Riviere
markdown: kramdown
remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-remote-theme
